### ISSUE TITLE
[error]The process '/bin/tar' failed with exit code 2

### ISSUE THREAD

**Issue by bluelovers** [actions/setup-node#116]
```
Run actions/setup-node@master
  with:
    node-version: 13
    always-auth: false
/bin/tar --version
tar (GNU tar) 1.29
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/2036e974-4339-482b-82eb-cdb09db0a167 -f /home/runner/work/_temp/f37bd59e-bdbe-4b4d-a5c2-6e0540d2eca3

gzip: stdin: unexpected end of file
/bin/tar: Unexpected EOF in archive
/bin/tar: Unexpected EOF in archive
##[error]The process '/bin/tar' failed with exit code 2
```

**Comment by shilangyu** [comment]
Re-running the workflow did work. Weird one-time error

**Comment by steph2282** [comment]
So it's fixed?

**Comment by TrentScholl** [comment]
I've been getting this error frequently over the past 2 days. Re-running usually fixes it, but we're seeing a lot of first time builds fail.

**Comment by IvanBioRender** [comment]
Still getting this issue 4 days later. Are there any updates?

**Comment by peaceiris** [comment]
Still getting this issue. Are there any updates?
https://github.com/peaceiris/actions-gh-pages/runs/478664577?check_suite_focus=true#step:4:19

**Comment by harrywhite4** [comment]
I had this come up several times today aswell. Seems to be an intermittent problem

**Comment by HudsonWu** [comment]
I've been getting the problem of long execution time today, and sometimes had this error('/bin/tar failed').  but there were no such problems yesterday.

**Comment by jayp0521** [comment]
My pipeline keeps failing because of this error. Has occurred before, but re-running multiple times today has not fixed the issue.

**Comment by IvanBioRender** [comment]
I posted a forum thread, hoping to get some kind of response from Github: https://github.community/t5/GitHub-Actions/actions-setup-node-v1-The-process-bin-tar-failed-with-exit-code/m-p/48590#M7221

**Comment by ericsciple** [comment]
I'll look into this shortly (next couple hours). Sounds like incomplete download, prob not checking HTTP code. Probably needs retries too.

**Comment by ericsciple** [comment]
OK i think i see the bug. It looks like error handling on dest stream (file stream), but not the response body stream. Working on it... Also looks like retry around getting a successful HTTP code, but no retry when reading body. So i'll add that too.

**Comment by ericsciple** [comment]
working in progress here https://github.com/actions/toolkit/pull/369

i still have a few more things to add to the PR...

**Comment by ericsciple** [comment]
also related to https://github.com/actions/virtual-environments/issues/42

**Comment by huan** [comment]
I still have this issue today, and retry does not seem fix that every time. 

https://github.com/wechaty/wechaty/runs/494081908#step:3:16

**Comment by AlCalzone** [comment]
Still happening to me every time Dependabot does its weekly update PR run. About half of my workflows fail due to this.

**Comment by ericsciple** [comment]
The tar issue was fixed.

**Comment by munrocket** [comment]
@ericsciple so you just retring to download?
Seems the same problem with actions/cache/issues/267

**Comment by wzhdaag** [comment]
I still see this issue.

I am downloading a tar.gz file from https://github.com/adoptium/temurin17-binaries/releases via our internal Artifactory's as proxy. 

Re-run helps.

**Comment by hydrolucid** [comment]
Getting this error quite a bit, have to re-run jobs multiple times to get successful runs.

**Comment by raymelon** [comment]
If anyone ever get this error in NextJS, please make sure that the artifact job is using `./.next` directory as path.

Before:
```yml
- name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
```

After:
```yml
- name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.next
```
