### ISSUE TITLE
v3.8.0 - "Cache folder paths are not retrieved for..."

### ISSUE THREAD

**Issue by sammarks** [actions/setup-node#828]
**Description:**
It looks like there might have been a breaking change in the latest version of the action. With the following configuration:

```yaml
- uses: actions/setup-node@v3
  with:
    node-version: 18
    cache: 'pnpm'
```

I'm getting during the cleanup step:

```
Cache folder paths are not retrieved for pnpm with cache-dependency-path = 
```

**Action version:**
v3.8.0 - This only started happening within the last 2 hours, and 3.8.0 was released 2 hours ago so that makes me believe there's an issue with the latest release.

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Node 18, PNPM 7.9.0

**Repro steps:**  
Create a workflow with the following step:

```yaml
- uses: actions/setup-node@v3
  with:
    node-version: 18
    cache: 'pnpm'
```

**Expected behavior:**
I expect the post-setup step to succeed.

**Actual behavior:**
It fails with an error message instead.

**Comment by urbanisierung** [comment]
Can confirm. Getting the same error with the latest version (`3.8.0`) - works again by downgrading to version `3.7.0`.

**Comment by dmitry-shibanov** [comment]
Hello everyone. Could you please provide a public repository to take a look at the build?

**Comment by dmitry-shibanov** [comment]
Hello everyone. It looks like the `pnpm store path --silent` command produces the warning regarding to workspaces. Could you please try to add `pnpm-workspace.yaml` or remove `workspaces` section from package.json ?

**Comment by sammarks** [comment]
Ah, could it be warnings output by `pnpm store path` before outputting the store path? I have an `NPM_TOKEN` variable in my `.npmrc` file. Since I do installation in another step, that variable isn't set during the Node setup step. PNPM throws a warning at the beginning of execution saying that variable isn't set, but then it outputs properly.

In the past, I believe the node setup action has just ignored the warnings and used the last line of output. Perhaps something was changed with the 3.8 release that made it try and interpret the first line as the result instead?

**Comment by bryanspears** [comment]
Whatever it was, it was a breaking change with a minor version bump. Affected Actions for us as well. :smile:

**Comment by t-jimbo** [comment]
The error above-mentioned is resolved, but it does not works for me.
It still fails during the post job cleanup while message is different as follows:

```
Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

I tried with the following step:

```
- uses: actions/setup-node@main
  with:
    node-version: 18
    cache: 'pnpm'
```

**Comment by chrisadubois** [comment]
bumping back to 3.7.0 for us also worked

**Comment by plato-juan** [comment]
> Hello everyone. Could you please try to use `actions/setup-node@main` to confirm that it works for you?

It worked for me after updating it to `actions/setup-node@main`

**Comment by dmitry-shibanov** [comment]
Hello @chrisadubois. If the repository is public could you please provide a build ?

**Comment by t-jimbo** [comment]
> Which versions of Nodejs and Pnpm do you use? Do you use composite action? Could you please add a step before cleanups to check that path: /home/runner/setup-pnpm/node_modules/.bin/store/v3 exists ?

Ah, sorry. It was my fault.
It worked after changing `path` provided for `actions/cache` from `node_modules` to `'**/node_modules'`.
It seems cache path is no longer resolved with just `node_modules`.

<details><summary>[FYI] worked with following:</summary>


```
- uses: actions/checkout@v3 
- uses: pnpm/action-setup@v2
  with:
    version: 8
  
- uses: actions/setup-node@main
  with:
    node-version: 18
    cache: 'pnpm'

- uses: actions/cache@v3
  id: pnpm-cache
  with:
    path: '**/node_modules'
    key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    restore-keys: |
      ${{ runner.os }}-pnpm-store-
  
- name: Install dependencies
  if: steps.pnpm-cache.outputs.cache-hit != 'true'
  run: pnpm install --frozen-lockfile
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

</details>

**Comment by jimjasson** [comment]
> Hello everyone. Could you please try to use actions/setup-node@main to confirm that it works for you?

@dmitry-shibanov Thanks for the quick fix here -- do you have an ETA for when this will be released?

**Comment by dmitry-shibanov** [comment]
Hello everyone. We released a new version of setup-node ([3.8.1](https://github.com/actions/setup-node/releases/tag/v3.8.1)). For now I'm going to close the issue.

**Comment by decline** [comment]
Still not working for me, using `actions/setup-node@v3` (5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d). Getting the following error:

```
Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

I'm using the action like this:

```yaml
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        cache: pnpm
```

**Comment by dmitry-shibanov** [comment]
Hello @decline. Could you please send the public build ?

**Comment by netroy** [comment]
We are also affected by this issue. I just tried downgrading to `3.7.0`, but still got the error. [Here is the last failed job](https://github.com/n8n-io/n8n/actions/runs/5929792543/job/16078321446).

Looking at the logs, `pnpm` says that the store is located at `/home/runner/.pnpm-store/`.
But, `actions/setup-node` says that the store is located at `/home/runner/setup-pnpm/node_modules/.bin/store/v3`.

I'm guessing this is some kind of a path conflict with `pnpm/action-setup`, and there might be two `pnpm` binaries.
