### ISSUE TITLE
Prefer `node-version-file: package.json` over $PATH by default

### ISSUE THREAD

**Issue by fregante** [actions/setup-node#912]
**Description:**

```yml
- uses: actions/setup-node@v5
```

Currently this uses what's available in $PATH, but I reckon it should prefer what the user _already_ specified as a compatible node version in the package.json.

**Justification:**

It feels strange that a project clearly and "natively" specifies what version it's expected to run on, but the environment ignores it, requiring further config.

I love that `node-version-file: package.json` is possible now, but I wish I didn't have to clutter all of my jobs with

```yml
- uses: actions/setup-node@v4
  with: 
    node-version-file: package.json

. . . 


- uses: actions/setup-node@v4
  with: 
    node-version-file: package.json

. . .

- uses: actions/setup-node@v4
  with: 
    node-version-file: package.json
```

The drawback is that in the rare situation where the user wants to use what's in PATH, as opposed to what's in package.json, now they'd need something like `node-version: PATH`. But again this feels like it should be the minority.

**Are you willing to submit a PR?**

Potentially

**Comment by marko-zivic-93** [comment]
Hello @fregante 
Thank you for creating this issue. We will investigate and come back to you as soon as we have some feedback.

**Comment by aparnajyothi-y** [comment]
Hello @fregante, We've merged the fix for the issue as part of another issue. Could you please try to use actions/setup-node@main to confirm that it works as expected?

**Comment by aparnajyothi-y** [comment]
Hello @fregante, Thank you for testing. 
Could you please replace the setup-action repository actions/setup-node@v4 in your workflow with actions/setup-node@main because we have merged the code as part of this [PR](https://github.com/actions/setup-node/pull/921) and yet to release.
Please replace the branch with main and update the results. Hope that should fulfil your requirement.

**Comment by fregante** [comment]
## without node-version-file, on `@main` ❌ 

Still no luck

<img width="300" alt="Screenshot" src="https://github.com/actions/setup-node/assets/1402241/17e8d101-1905-4cc0-a9e8-e724ba39288c">

- package.json: https://github.com/fregante/webext-storage/blob/347dccdb09eb2d3b4a71e23b1c6b2ac2ccd22272/package.json#L60-L62
- workflow: https://github.com/fregante/webext-storage/blob/347dccdb09eb2d3b4a71e23b1c6b2ac2ccd22272/.github/workflows/ci.yml#L12
- run using the default v18 instead of the `engines` field: https://github.com/fregante/webext-storage/actions/runs/7570275738/job/20615307302

**Comment by fregante** [comment]
> we have merged the code as part of this [PR](https://github.com/actions/setup-node/pull/921)

That PR is unrelated to this feature request.

The tests on `main` specifically verify the opposite of this feature request, right?

https://github.com/ThisIsManta/setup-node/blob/d86ebcd40b3cb50b156bfa44dd277faf38282d12/__tests__/main.test.ts#L185-L187

**Comment by hilja** [comment]
Great issue and great research. I was just wondering the same thing, would be great if the version would just work™

**Comment by kleinfreund** [comment]
Additionally, this would provide a nice way to configure both the node _and_ npm version. Currently, actions/setup-node will install a npm version that does generally not match `pkg.engines.npm`. If one wants to ensure that the npm version is the same as the one used locally, one has to run `npm install --global npm@...` after `actions/setup-node` which is cumbersome.

**Comment by fregante** [comment]
@kleinfreund that's unrelated, this request is exclusively about changing a default. The action already reads the node version from package.json on request.

**Comment by mk-pmb** [comment]
I added this one to my suggested way of merging all the version number oracles [over here in issue 939](https://github.com/actions/setup-node/issues/939#issuecomment-2162667149).

**Comment by v-aparnajyothi-y** [comment]
Hi @y-nk, thank you for this feature request. After internal evaluation and considering existing usage patterns, we've decided to keep the current precedence behavior (node-version > node-version-file). Reversing this logic would be a breaking change for a large number of workflows, and at this time we’re not planning to introduce it as a feature.

We do recognize the value of the fallback behavior you proposed, especially for monorepo setups. We're closing this issue for now and we'll keep this suggestion in mind for future iterations if we explore safer ways to improve version resolution without impacting backward compatibility.
Please feel free to reach us in case of any further concerns or clarification to reopen this issue:)

**Comment by y-nk** [comment]
@aparnajyothi-y i'm not sure to follow why i'm mentioned in @fregante 's issue 🤔

**Comment by fregante** [comment]
> breaking change for a large number of workflows

Isn't that what semver is for? No CI is going to serendipitously break because the current version remains unchanged. 

What's the point of breaking versions if no breaking changes are allowed?
